version: "2"

x-redash-service: &redash-service
  build:
    context: ../
  volumes:
    - ../:/app
  depends_on:
    - redis
  env_file: ~/redash/.env
  restart: unless-stopped

services:
  
  server:
    <<: *redash-service
    command: server
    container_name: builder.server
    ports:
      - "5000:5000"
    environment:
      REDASH_WEB_WORKERS: 4
  
  scheduler:
    <<: *redash-service
    command: scheduler
    container_name: builder.scheduler
    environment:
      QUEUES: "celery"
      WORKERS_COUNT: 1

  general_worker:
    <<: *redash-service
    command: worker
    container_name: builder.general_worker
    environment:
      QUEUES: "emails,default"
      WORKERS_COUNT: 1
  
  scheduled_worker:
    <<: *redash-service
    command: worker
    container_name: builder.worker
    environment:
      QUEUES: "scheduled_queries,schemas"
      WORKERS_COUNT: 1
  
  adhoc_worker:
    <<: *redash-service
    command: worker
    container_name: builder.adhoc_worker
    environment:
      QUEUES: "queries"
      WORKERS_COUNT: 2
  
  redis:
    image: redis:5.0-alpine
    container_name: builder.redis
    restart: unless-stopped
