version: "2"

x-redash-service: &redash-service
  build:
    context: ../
    args:
      skip_frontend_build: "true"
  volumes:
    - ../:/app
  depends_on:
    - redis
  env_file: ~/redash/.env
  restart: unless-stopped

services:
  
  server:
    <<: *redash-service
    command: server
    container_name: builder.server
    ports:
      - "5000:5000"
    environment:
      REDASH_WEB_WORKERS: 4
    networks:
      - fidap_builder_db_net
  
  scheduler:
    <<: *redash-service
    command: scheduler
    container_name: builder.scheduler
    environment:
      QUEUES: "celery"
      WORKERS_COUNT: 1
    networks:
      - fidap_builder_db_net

  general_worker:
    <<: *redash-service
    command: worker
    container_name: builder.general_worker
    environment:
      QUEUES: "emails,default"
      WORKERS_COUNT: 1
    networks:
      - fidap_builder_db_net
  
  scheduled_worker:
    <<: *redash-service
    command: worker
    container_name: builder.worker
    environment:
      QUEUES: "scheduled_queries,schemas"
      WORKERS_COUNT: 1
    networks:
      - fidap_builder_db_net
  
  adhoc_worker:
    <<: *redash-service
    command: worker
    container_name: builder.adhoc_worker
    environment:
      QUEUES: "queries"
      WORKERS_COUNT: 2
    networks:
      - fidap_builder_db_net
  
  redis:
    image: redis:5.0-alpine
    container_name: builder.redis
    restart: unless-stopped
    networks:
      - fidap_builder_db_net

  db:
    image: postgres:12
    restart: unless-stopped
    container_name: fidap-builder.db
    ports:
      - 5442:5432
    environment:
      POSTGRES_USER: fidapbuilder
      POSTGRES_PASSWORD: EJUuCtLDXd73gpvb
      POSTGRES_DB: builder_db
    networks:
      - fidap_builder_db_net

networks:
  fidap_builder_db_net:
